import { QuizDefinition } from './quiz.models';

export const dayNineteenQuiz: QuizDefinition = {
  id: 'day-19',
  day: 19,
  title: 'keyof、typeof 與索引存取型別：避免重複維護型別',
  estimatedMinutes: 12,
  questions: [
    {
      id: 'day-19-01',
      number: 1,
      kind: 'choice',
      learningGoal: '區分 JavaScript 的 typeof 與 TypeScript 型別位置的 typeof',
      prompt: '以下哪一項最準確地描述 type Labels = typeof questionTypeLabels？',
      hint: '先判斷這行是在 Runtime 執行，還是只建立編譯期型別名稱。',
      options: [
        { id: 'A', label: 'Runtime 會建立一個名為 Labels 的物件' },
        { id: 'B', label: 'TypeScript 會參照 questionTypeLabels 目前的型別，建立一個型別別名' },
        { id: 'C', label: '它會回傳字串 "object"' },
        { id: 'D', label: '它會在執行時驗證物件的所有欄位' },
      ],
      correctAnswer: 'B',
      explanation: '型別位置的 typeof 只供 TypeScript 參照既有值的型別，不會建立 Runtime 值，也不會回傳 JavaScript 的 typeof 字串。',
    },
    {
      id: 'day-19-02',
      number: 2,
      kind: 'choice',
      learningGoal: '推論 keyof typeof 的鍵名聯集',
      prompt: '以下程式中，kind 可以被指定哪些字串？',
      hint: '先用 typeof 取得物件型別，再查看 keyof 會取哪一層資訊。',
      code: 'const labels = {\n  choice: "選擇題",\n  fill: "填空題",\n};\n\ntype QuestionType = keyof typeof labels;\nlet kind: QuestionType = "choice";',
      options: [
        { id: 'A', label: '只有 "choice"' },
        { id: 'B', label: '只有 "選擇題" 與 "填空題"' },
        { id: 'C', label: '"choice" 或 "fill"' },
        { id: 'D', label: '任意 string' },
      ],
      correctAnswer: 'C',
      explanation: 'typeof labels 是物件型別，keyof 取出的是物件的鍵名，因此 QuestionType 是 "choice" | "fill"，不是值 "選擇題" | "填空題"。',
    },
    {
      id: 'day-19-03',
      number: 3,
      kind: 'choice',
      learningGoal: '辨識值不能直接作為索引存取型別的索引',
      prompt: '以下宣告無法通過型別檢查，問題在哪裡？',
      hint: 'Question[...] 的方括號內需要的是型別，不是一般值變數。',
      code: 'type Question = {\n  prompt: string;\n  type: "choice" | "fill";\n};\n\nconst key = "prompt";\ntype Prompt = Question[key];',
      options: [
        { id: 'A', label: 'Question 不能有兩個 property' },
        { id: 'B', label: 'key 是值，不能直接作為型別索引；需要使用字串字面值型別或 typeof key 並確認它是合法鍵名' },
        { id: 'C', label: 'prompt 必須改成 number' },
        { id: 'D', label: '索引存取型別不能取得物件 property' },
      ],
      correctAnswer: 'B',
      explanation: '索引存取型別的索引位置在型別層運作。key 是 Runtime 值，不能直接寫進 Question[key]；可以直接使用 Question["prompt"]，或讓索引具有 keyof Question 的型別。',
    },
    {
      id: 'day-19-04',
      number: 4,
      kind: 'exact-text',
      learningGoal: '辨識從物件型別取得鍵名的運算子',
      prompt: '要取得 Question 型別的所有合法鍵名，應使用哪個 TypeScript 運算子？只輸入運算子名稱。',
      hint: '結果應是 "id" | "prompt" | "type" 這種鍵名聯集。',
      acceptedAnswers: ['keyof'],
      explanation: 'keyof Question 會產生 "id" | "prompt" | "type"，也就是該物件型別宣告的鍵名聯集。',
    },
    {
      id: 'day-19-05',
      number: 5,
      kind: 'code-fill',
      learningGoal: '組合 typeof 與 keyof 從值推導鍵名型別',
      prompt: '請補上缺少的型別運算子，讓 QuestionType 隨 labels 物件的鍵名更新。',
      hint: '先從值取得型別，再從物件型別取得鍵名；兩個運算子由右往左理解。',
      code: 'const labels = {\n  choice: "選擇題",\n  fill: "填空題",\n};\n\ntype QuestionType = ____ typeof labels;',
      acceptedAnswers: ['keyof'],
      explanation: '完整寫法是 type QuestionType = keyof typeof labels。填空位置前已經保留 typeof labels，因此只需補上 keyof。',
    },
  ],
};
