import { QuizDefinition } from './quiz.models';

export const dayTwentyTwoQuiz: QuizDefinition = {
  id: 'day-22', day: 22, title: 'infer：理解函式庫如何推導型別', estimatedMinutes: 12,
  questions: [
    { id: 'day-22-01', number: 1, kind: 'choice', learningGoal: '理解 infer 的作用位置', prompt: 'type ElementOf<T> = T extends (infer Item)[] ? Item : T 中的 Item 是什麼？', hint: '先看 Item 出現在陣列元素的位置，還是完整陣列的位置。', options: [{ id: 'A', label: '比對陣列結構時暫時推導出的元素型別' }, { id: 'B', label: '陣列第一個元素的實際值' }, { id: 'C', label: '固定名稱為 Item 的全域型別' }, { id: 'D', label: '一定等於 string 的型別' }], correctAnswer: 'A', explanation: 'infer Item 讓 TypeScript 在條件型別比對陣列時擷取元素型別；Item 只存在於型別推導過程。' },
    { id: 'day-22-02', number: 2, kind: 'choice', learningGoal: '從函式結構取得回傳型別', prompt: '以下型別的結果是什麼？', hint: 'infer Output 放在函式箭頭的哪一側？', code: 'type OutputOf<T> = T extends () => infer Output\n  ? Output\n  : never;\n\ntype Result = OutputOf<() => boolean>;', options: [{ id: 'A', label: 'boolean' }, { id: 'B', label: '() => boolean' }, { id: 'C', label: 'never' }, { id: 'D', label: 'unknown[]' }], correctAnswer: 'A', explanation: '來源符合函式型別，且 infer Output 位於回傳位置，因此 Result 是 boolean。' },
    { id: 'day-22-03', number: 3, kind: 'choice', learningGoal: '區分取出 Promise 與取出完成值', prompt: '若呼叫端需要 await 後的 Question，以下宣告問題在哪裡？', hint: '先寫出 ReturnType 的結果，再判斷它是否還包著 Promise。', code: 'type LoadQuestion = () => Promise<Question>;\n\ntype LoadedQuestion = ReturnType<LoadQuestion>;', options: [{ id: 'A', label: 'ReturnType 會得到 Promise<Question>，還需要 Awaited 或等價拆解' }, { id: 'B', label: 'ReturnType 只能用在同步函式' }, { id: 'C', label: 'Question 不能作為泛型參數' }, { id: 'D', label: 'ReturnType 會自動解開 Promise，因此結果已是 Question' }], correctAnswer: 'A', explanation: '非同步函式的回傳型別是 Promise<Question>；ReturnType 不會自動取出 await 後的完成值。' },
    { id: 'day-22-04', number: 4, kind: 'exact-text', learningGoal: '判斷條件不成立時的結果', prompt: '在 type OutputOf<T> = T extends () => infer Output ? Output : never 中，當 T 不是函式時會得到什麼型別？', hint: '查看冒號後的型別。', acceptedAnswers: ['never'], explanation: '不符合函式結構時選擇不成立的分支，也就是 never。' },
    { id: 'day-22-05', number: 5, kind: 'code-fill', learningGoal: '使用 infer 取出 Promise 完成值', prompt: '請補上關鍵字，讓 TypeScript 推導 Promise 裡的型別，命名為 Value。', hint: '要在比對結構中取得型別，並替它取名，該使用哪個關鍵字？', code: 'type Unwrap<T> = T extends Promise<____ Value> ? Value : never;\ntype Loaded = Unwrap<Promise<Question>>;', acceptedAnswers: ['infer'], explanation: 'infer Value 會從 Promise<Question> 取出 Question；條件成立時，使用 Value 作為結果型別。' },
  ],
};
