import { QuizDefinition } from './quiz.models';

export const dayNineteenQuiz: QuizDefinition = {
  id: 'day-19',
  day: 19,
  title: 'keyof、typeof 與索引存取型別：避免重複維護型別',
  estimatedMinutes: 12,
  questions: [
    {
      id: 'day-19-01',
      number: 1,
      kind: 'choice',
      learningGoal: '區分 JavaScript 的 typeof 與 TypeScript 型別位置的 typeof',
      prompt: '以下哪一項最準確地描述 type Labels = typeof questionTypeLabels？',
      hint: '先判斷這行會在程式執行時產生結果，還是只宣告型別別名。',
      options: [
        { id: 'A', label: '執行時會建立一個名為 Labels 的物件' },
        { id: 'B', label: 'TypeScript 會參照 questionTypeLabels 目前的型別，建立一個型別別名' },
        { id: 'C', label: '它會回傳字串 "object"' },
        { id: 'D', label: '它會在執行時驗證物件的所有欄位' },
      ],
      correctAnswer: 'B',
      explanation: '型別位置的 typeof 只供 TypeScript 參照既有值的型別，不會在執行時建立新的值，也不會回傳 JavaScript 的 typeof 字串。',
    },
    {
      id: 'day-19-02',
      number: 2,
      kind: 'choice',
      learningGoal: '推論 keyof typeof 的鍵名聯集',
      prompt: '以下程式中，publishStatus 可以被指定哪些字串？',
      hint: '先用 typeof 取得物件型別，再查看 keyof 會取哪一層資訊。',
      code: 'const statusLabels = {\n  draft: "草稿",\n  published: "已發布",\n};\n\ntype Status = keyof typeof statusLabels;\nlet publishStatus: Status = "draft";',
      options: [
        { id: 'A', label: '只有 "draft"' },
        { id: 'B', label: '只有 "草稿" 與 "已發布"' },
        { id: 'C', label: '"draft" 或 "published"' },
        { id: 'D', label: '任意 string' },
      ],
      correctAnswer: 'C',
      explanation: 'typeof statusLabels 是物件型別，keyof 取出的是物件的鍵名，因此 Status 是 "draft" | "published"，不是值 "草稿" | "已發布"。',
    },
    {
      id: 'day-19-03',
      number: 3,
      kind: 'choice',
      learningGoal: '辨識值不能直接作為索引存取型別的索引',
      prompt: '以下宣告無法通過型別檢查，問題在哪裡？',
      hint: 'Question[...] 的方括號內需要的是型別，不是一般值變數。',
      code: 'type Question = {\n  prompt: string;\n  type: "choice" | "fill";\n};\n\nconst key = "prompt";\ntype Prompt = Question[key];',
      options: [
        { id: 'A', label: 'Question 不能有兩個欄位' },
        { id: 'B', label: 'key 是值，不能直接作為型別索引；需要使用字串字面值型別或 typeof key 並確認它是合法鍵名' },
        { id: 'C', label: 'prompt 必須改成 number' },
        { id: 'D', label: '索引存取型別不能取得物件欄位' },
      ],
      correctAnswer: 'B',
      explanation: '索引存取型別的索引位置在型別層運作。key 是變數，不能直接寫進 Question[key]；可以直接使用 Question["prompt"]，或使用 Question[typeof key] 取得變數型別後再索引。',
    },
    {
      id: 'day-19-04',
      number: 4,
      kind: 'exact-text',
      learningGoal: '辨識從物件型別取得鍵名的運算子',
      prompt: '要取得 Question 型別的所有合法鍵名，應使用哪個 TypeScript 運算子？只輸入運算子名稱。',
      hint: '結果應是 "id" | "prompt" | "type" 這種鍵名聯集。',
      acceptedAnswers: ['keyof'],
      explanation: 'keyof Question 會產生 "id" | "prompt" | "type"，也就是該物件型別宣告的鍵名聯集。',
    },
    {
      id: 'day-19-05',
      number: 5,
      kind: 'code-fill',
      learningGoal: '使用索引存取型別取得欄位型別',
      prompt: '補上鍵名型別，讓 QuestionScore 取得 Question 中 score 欄位的型別。請使用雙引號。',
      hint: '方括號內需要指定欄位名稱的字串字面值型別。',
      code: 'type Question = {\n  prompt: string;\n  score: number;\n};\n\ntype QuestionScore = Question[____];',
      acceptedAnswers: ['"score"'],
      explanation: 'Question["score"] 取得 score 欄位的型別，因此 QuestionScore 是 number。修改來源欄位型別後，這個型別別名也會跟著更新。',
    },
  ],
};
